#!/bin/sh

gitbranchsis=node_modules/git-branch-is/bin/git-branch-is.js

node $gitbranchsis -q main
if [[ $? == 0 ]]; then
    echo "On main branch. Will build and ship to server"
    npm version patch
    echo "Bumping version up a patch"
else
    node $gitbranchsis -q staging
    if [[ $? == 0 ]]; then
        echo "Skipping version bump, not on main-branch."
    else
        echo "Ignore versioning"
    fi
fi