#!/bin/sh

gitbranchsis=node_modules/git-branch-is/bin/git-branch-is.js

node $gitbranchsis -q main
if [[ $? == 0 ]]; then
    echo "On main branch. Will build and ship to server"
    npm run build
    echo "Shipping the production bundle to the server"
    rsync -arvz -e 'ssh -p 2244' --progress $(pwd)/dist/ jeth@ton-618.ddns.net:/home/jeth/apps/crypto-price-sniffer/production
else
    node $gitbranchsis -q add-webpack
    if [[ $? == 0 ]]; then
        echo "Shipping the staging bundle to the server"
        #rsync -arvz -e 'ssh -p 2244' --progress $(pwd)/dist/ jeth@ton-618.ddns.net:/home/jeth/apps/crypto-price-sniffer/staging
    else
        echo "Skipping build and deployment"
    fi
fi